### ISSUE TITLE
Make this a contract repo

### ISSUE THREAD

**Issue by NoelJacob** [ton-defi-org/tonstarter-contracts#3]
I guess it fits good and is easier to start working.

**Comment by talkol** [comment]
not sure I understand the issue, can you explain a bit more?

**Comment by NoelJacob** [comment]
Really sorry got lost in some thought, I meant make it a template repo.

**Comment by mrbonezy** [comment]
From the docs:

"Creating a repository from a template is similar to forking a repository, but there are important differences:

A new fork includes the entire commit history of the parent repository, while a repository created from a template starts with a single commit.
Commits to a fork don't appear in your contributions graph, while commits to a repository created from a template do appear in your contribution graph.
A fork can be a temporary way to contribute code to an existing project, while creating a repository from a template starts a new project quickly."

@talkol any objections?

**Comment by talkol** [comment]
done, @NoelJacob is this ok now?
